version: "3.8"

services:
  frontend:
    volumes:
      - ./frontend:/app            # mount host code
      - /app/node_modules         # keep container’s modules
    environment:
      - NODE_ENV=development
    command: yarn dev             # or npm run dev

  backend:
    volumes:
      - ./backend:/app
      - /app/venv                 # keep container’s venv
    environment:
      - ENVIRONMENT=development
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
