name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    # Python Setup
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install Python dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run Python tests
      run: |
        cd backend
        pytest --cov=app --cov-report=xml

    # Node.js Setup
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install Node.js dependencies
      run: |
        cd frontend
        npm ci

    - name: Run frontend tests
      run: |
        cd frontend
        npm run test

    - name: Run frontend type check
      run: |
        cd frontend
        npm run type-check

    # Playwright Setup
    - name: Install Playwright browsers
      run: |
        cd frontend
        npx playwright install --with-deps chromium firefox webkit

    - name: Run Playwright tests
      run: |
        cd frontend
        npm run test:e2e

    # Docker Build Test
    - name: Test Docker build
      run: docker-compose build

    # Upload coverage reports
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./backend/coverage.xml
        flags: backend
        name: codecov-umbrella

    # Upload Playwright report on failure
    - name: Upload Playwright report
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: frontend/playwright-report
        retention-days: 30 